#!/bin/bash

filename="$HOME/.people"

if [ ! -f "$filename" ]; then
  touch "$filename"
fi

case "$1" in
  add)
    if [ $# -ne 2 ]; then
      echo "Usage: people add <name>"
      exit 1
    fi
    date=$(date +%s)
    echo "$date	add	$2" >> "$filename"
    ;;
  list)
    if [ $# -ne 1 ]; then
      echo "Usage: people list"
      exit 1
    fi
    grep "^.*	add	.*$" "$filename" | awk '{print $3}' | sort | uniq
    ;;
  contact)
    person=$("$0" list | fzf)
    if [ -z "$person" ]; then
      exit 0
    fi

    date=$(date +%s)
    echo "$date	contact	$person" >> "$filename"
    ;;
  goal)
    person=$("$0" list | fzf)
    if [ -z "$person" ]; then
      exit 0
    fi

    read -r -p "Goal (in days): " goal
    if [ -z "$goal" ]; then
      exit 0
    fi

    date=$(date +%s)
    echo "$date	goal	$person	$goal" >> "$filename"
    ;;
  note)
    person=$("$0" list | fzf)
    if [ -z "$person" ]; then
      exit 0
    fi

    read -r -p "Note: " note
    if [ -z "$note" ]; then
      exit 0
    fi

    date=$(date +%s)
    echo "$date	note	$person	$note" >> "$filename"
    ;;
  show)
    while read -r line; do
      date=$(echo "$line" | awk '{print $1}')
      human_readable_date=$(date -d "@$date" "+%Y-%m-%d %H:%M:%S")
      echo "$human_readable_date" "$line"
    done < "$filename"
    ;;
  summary)
    (
      echo "Name	Last Contacted	Contact goal"
      "$0" list | while read -r name; do
        name=$(echo "$name" | awk '{print $1}')
        date=$(echo "$name" | awk '{print $1}')

        goal=$(grep ".*	goal	$name" "$filename" | tail -n 1 | awk '{print $4}')

        last_contacted=$(grep ".*	contact	$name$" "$filename" | tail -n 1 | awk '{print $1}')
        if [ -z "$last_contacted" ]; then
          if [ -n "$goal" ]; then
            last_contacted=$(printf "\033[0;31mnever\033[0m")
          else
            last_contacted=$(printf "never")
          fi
        else
          current_date=$(date +%s)
          difference=$(( "$current_date" - "$last_contacted"))
          last_contacted=$(awk -v diff="$difference" -v goal="$goal" '
          BEGIN {
            red="\033[0;31m"
            yellow="\033[0;33m"
            green="\033[0;32m"
            white="\033[0;37m"
            clear="\033[0m"

            days=diff / 86400
            hours=diff % 86400 / 3600
            minutes=diff % 3600 / 60
            seconds=diff % 60

            color=green
            if (days>goal) {
              color=red
            }

            printf "%s%d:%02d:%02d:%02d%s",
              color,
              days,
              hours,
              minutes,
              seconds,
              clear
          }')
        fi

        if [ -z "$goal" ]; then
          goal="none"
        fi
        echo "$name	$last_contacted	$goal"
      done
    ) | column -t -s $'\t'
    ;;
  behind)
    "$0" list | while read -r name; do
      goal=$(grep ".*	goal	$name" "$filename" | tail -n 1 | awk '{print $4}')
      if [ -z "$goal" ]; then
        continue
      fi

      last_contacted=$(grep ".*	contact	$name$" "$filename" | tail -n 1 | awk '{print $1}')
      if [ -z "$last_contacted" ]; then
        echo "$name	∞"
      else
        current_date=$(date +%s)
        difference=$(( current_date - last_contacted))
        days=$(( difference / 86400 ))
        if [ $days -gt "$goal" ]; then
          echo "$name	$days days overdue"
        fi
      fi
    done | column -t -s $'\t'
    ;;
  edit)
    $EDITOR "$filename"
    ;;
  *)
    echo "Usage: people <command>"
    echo "Commands:"
    echo "  add <name> - add a person"
    echo "  list - list people"
    echo "  contact - contact a person"
    echo "  goal - set a goal for a person"
    echo "  note - add a note for a person"
    echo "  show - print a list of events"
    echo "  summary - print a summary of people"
    echo "  behind - print a list of people behind on contact"
    echo "  edit - edit the people file"
    exit 1
    ;;
esac
